import { test, expect } from "./strict-fixture";
import { installSyntheticPortfolio, syntheticPortfolio } from "./reliability-fixture";
import { readFile } from "node:fs/promises";
import { unlockVaultWithPassphrase } from "../lib/vault-crypto";
import { validatePortfolio } from "../lib/portfolio-validation";

test("fund trade drafts, accounts, edit, delete, calendar and encrypted backup preserve accounting", async ({ page }) => {
  test.setTimeout(120_000);
  const fixture = syntheticPortfolio(4, 4, 100);
  Object.assign(fixture.seed.securities[0], { assetType: "fund", priceUnit: "10000", name: "合成投資信託" });
  await installSyntheticPortfolio(page, fixture);
  let saved = validatePortfolio(fixture.seed);
  await page.route("**/api/local/bootstrap", async (route) => {
    if (route.request().method() === "POST") {
      saved = route.request().postDataJSON();
      await route.fulfill({ status: 204 });
    } else await route.fulfill({ json: saved });
  });
  await page.goto("/");
  await page.getByRole("button", { name: /^取引(?:履歴)?$/u }).click();
  await page.getByRole("button", { name: "取引を追加" }).click();
  const form = page.locator("form.trade-modal");
  const quantity = form.getByLabel("口数", { exact: true });
  const price = form.getByLabel(/^基準価額/u);
  await quantity.fill(".");
  await price.fill("-");
  await expect(form.locator(".trade-preview")).toContainText("—");
  await expect(form.getByRole("button", { name: "端末に保存", exact: true })).toBeDisabled();
  await quantity.fill("10,000");
  await price.fill("16,000.01");
  await form.getByLabel("証券口座", { exact: true }).selectOption("__custom__");
  await form.getByLabel("証券会社名", { exact: true }).fill("検証用証券");
  await form.getByRole("button", { name: "端末に保存", exact: true }).click();
  await expect.poll(() => saved.transactions.length).toBe(5);
  const created = saved.transactions.find((item) => item.source === "manual")!;
  expect(created).toMatchObject({ quantity: "10000", pricePerShare: "16000.01", grossAmount: "16000.01" });
  expect(saved.accounts.find((account) => account.id === created.accountId)?.broker).toBe("検証用証券");
  await page.getByRole("button", { name: /合成投資信託 .*を編集/u }).first().click();
  await quantity.fill("5,000");
  await form.getByRole("button", { name: "変更を端末に保存" }).click();
  await expect.poll(() => saved.transactions.find((item) => item.id === created.id)?.grossAmount).toBe("8000.005");
  await page.getByRole("tab", { name: "カレンダー", exact: true }).click();
  await expect(page.locator(".activity-calendar")).toBeVisible();
  await page.getByRole("button", { name: "前の月", exact: true }).click();
  await page.getByRole("button", { name: "一覧", exact: true }).click();
  await page.getByRole("button", { name: /^取引(?:履歴)?$/u }).click();
  await expect(page.getByRole("tab", { name: "カレンダー", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.getByRole("tab", { name: "頻度", exact: true }).click();
  await expect(page.locator(".activity-histogram")).toBeVisible();
  await page.getByRole("tab", { name: "一覧", exact: true }).click();
  await page.getByRole("button", { name: /合成投資信託 .*を削除/u }).first().click();
  await page.getByRole("alertdialog").getByRole("button", { name: "削除する", exact: true }).click();
  await expect.poll(() => saved.transactions.length).toBe(4);
  expect(saved.transactions.some((item) => item.id === created.id)).toBe(false);
  // Archiving an account keeps existing trades and makes it available when editing.
  await page.getByRole("button", { name: "取引を追加" }).click();
  await form.getByLabel("証券口座", { exact: true }).selectOption(created.accountId);
  await form.getByRole("button", { name: "選択中の証券口座を一覧から削除" }).click();
  await page.getByRole("alertdialog").getByRole("button", { name: "一覧から削除", exact: true }).click();
  await expect.poll(() => saved.accounts.find((account) => account.id === created.accountId)?.archivedAt).toBeTruthy();
  await form.getByRole("button", { name: "閉じる", exact: true }).click();
  await page.getByRole("button", { name: "設定", exact: true }).click();
  await page.getByRole("button", { name: "バックアップ", exact: true }).click();
  await page.getByRole("button", { name: "進む", exact: true }).click();
  const passphrase = "synthetic export passphrase only";
  await page.getByLabel("暗号化パスフレーズ", { exact: true }).fill(passphrase);
  await page.getByLabel("パスフレーズを再入力", { exact: true }).fill(passphrase);
  await page.getByRole("button", { name: "暗号化してダウンロード" }).click();
  const paintDelay = await page.evaluate(async () => {
    const started = performance.now();
    await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
    return performance.now() - started;
  });
  expect(paintDelay).toBeLessThan(500);
  await expect(page.getByText("暗号化ファイルを作成しました", { exact: true })).toBeVisible({ timeout: 60_000 });
  const [backup] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "暗号化ファイルを保存", exact: true }).click()]);
  const [recoveryFile] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "復旧キーを保存", exact: true }).click()]);
  expect(await readFile((await recoveryFile.path())!, "utf8")).toContain(await page.locator(".recovery-result code").innerText());
  const envelope = JSON.parse(await readFile((await backup.path())!, "utf8"));
  expect(JSON.stringify(envelope)).not.toContain("grossAmount");
  const restored = await unlockVaultWithPassphrase<typeof saved>(envelope, passphrase);
  expect(restored.data.transactions).toEqual(saved.transactions);
  expect(restored.data.accounts).toEqual(saved.accounts);
});
